name: hunter_csv
channels:
  - defaults
  - conda
  - conda-forge
dependencies:
  - python=3.9.12
  - autopep8=1.6.0
  - boto3=1.24.28
  - isort=5.9.3
  - pandas=1.4.2
  - pytest=7.2.2
  - pytest-cov=4.0.0
  - pip=23.0.1