name: hunter_csv
channels:
  - defaults
  - conda
  - conda-forge
dependencies:
  - python=3.9.12
  - pytest=7.2.2
  - pytest-cov=4.0.0
  - autopep8
  - GitPython=3.1.31
  - isort
  - pip
  - pip:
      - freezegun==1.2.2